#!/usr/bin/env guile
!#

;;; generate-rsc.scm — Read .env and emit a RouterOS setup script to stdout.
;;;
;;; Usage: guile generate-rsc.scm <env-file> > setup.rsc

(use-modules (ice-9 rdelim)
             (ice-9 regex)
             (srfi srfi-1))

(define (read-lines port)
  (let loop ((acc '()))
    (let ((line (read-line port)))
      (if (eof-object? line)
          (reverse acc)
          (loop (cons line acc))))))

(define (die msg)
  (format (current-error-port) "error: ~a\n" msg)
  (exit 1))

(define (read-env path)
  (if (not (file-exists? path))
      (die "Missing .env — copy .env.example and fill in values")
      (filter-map
       (lambda (line)
         (let ((m (string-match "^([A-Z_][A-Z0-9_]*)=(.+)$" line)))
           (and m (cons (match:substring m 1) (match:substring m 2)))))
       (call-with-input-file path read-lines))))

(define (required env key)
  (let ((v (assoc-ref env key)))
    (when (or (not v) (string=? v ""))
      (die (string-append "Required variable not set in .env: " key)))
    v))

(define (optional env key default)
  (let ((v (assoc-ref env key)))
    (if (and v (not (string=? v ""))) v default)))

(define (out . args)
  (for-each display args)
  (newline))

(define (generate env)
  (let* ((upstream-ssid  (required env "UPSTREAM_SSID"))
         (upstream-pass  (required env "UPSTREAM_WIFI_PASSWORD"))
         (travel-ssid    (required env "TRAVEL_SSID"))
         (travel-pass    (required env "TRAVEL_WIFI_PASSWORD"))
         (nextdns-id     (required env "NEXTDNS_PROFILE_ID"))
         (nextdns-name   (optional env "NEXTDNS_DEVICE_NAME" "apTravel"))
         (device-name    (optional env "DEVICE_NAME"         "apTravel"))
         (wg-port        (optional env "WG_LISTEN_PORT"      "13231"))
         (lan-ula        (optional env "LAN_ULA_PREFIX"      "fd88:1::1/64"))
         (private-key    (required env "AIRVPN_PRIVATE_KEY"))
         (mtu            (optional env "AIRVPN_MTU"          "1320"))
         (server-pubkey  (required env "AIRVPN_SERVER_PUBKEY"))
         (preshared-key  (required env "AIRVPN_PRESHARED_KEY"))
         (endpoint-ip    (required env "AIRVPN_ENDPOINT_IP"))
         (endpoint-port  (required env "AIRVPN_ENDPOINT_PORT"))
         (keepalive      (optional env "AIRVPN_KEEPALIVE"    "15"))
         (tunnel-ipv6    (required env "AIRVPN_TUNNEL_IPV6")))

    (out "# Generated by generate-rsc.scm")
    (out "# Model: hAP ax2 (C52iG-5HaxD2HaxD)")
    (out)

    (out "# --- Identity ---")
    (out "/system identity set name=" device-name)
    (out "/system note set show-at-login=no")
    (out "/system ntp client set enabled=yes")
    (out "/system ntp client servers add address=pool.ntp.org")
    (out)

    (out "# --- Users ---")
    (out "/user add name=root group=full")
    (out "# From your local machine, push your SSH public key:")
    (out "# ssh -4 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@192.168.88.1 \\")
    (out "#   \"/file print file=mykey.txt; file set mykey.txt contents=\\\"$(cat ~/.ssh/id_ed25519.pub)\\\"; /user ssh-keys import public-key-file=mykey.txt\"")
    (out)

    (out "# --- Bridge ---")
    (out "/interface bridge add name=bridge comment=defconf")
    (out)

    (out "# --- WiFi security profiles ---")
    (out "/interface wifi security")
    (out "add name=Upstream passphrase=\"" upstream-pass "\" ft=no")
    (out "add name=Travel   passphrase=\"" travel-pass "\"")
    (out)

    (out "# --- WiFi interfaces ---")
    (out "/interface wifi")
    (out "set [find default-name=wifi1] "
         "channel.band=5ghz-ax "
         "channel.skip-dfs-channels=all "
         "configuration.mode=station-bridge "
         "configuration.ssid=\"" upstream-ssid "\" "
         "security=Upstream "
         "security.ft=no "
         "security.ft-over-ds=no "
         "disabled=no")
    (out "set [find default-name=wifi2] disabled=yes")
    (out "add name=wifiTravel "
         "master-interface=wifi1 "
         "configuration.mode=ap "
         "configuration.ssid=\"" travel-ssid "\" "
         "security=Travel "
         "disabled=no")
    (out)

    (out "# --- Bridge ports ---")
    (out "/interface bridge port")
    (out "remove [find interface=wifi1]")
    (out "add bridge=bridge interface=wifiTravel")
    (out)

    (out "# --- Interface lists ---")
    (out "/interface list member")
    (out "add interface=wifi1  list=WAN")
    (out "add interface=airvpn list=WAN")
    (out)

    (out "# --- WAN DHCP client ---")
    (out "/ip dhcp-client add interface=wifi1 default-route-tables=main name=wan-dhcp comment=defconf")
    (out)

    (out "# --- Management restrictions ---")
    (out "/ip neighbor discovery-settings set discover-interface-list=LAN")
    (out "/tool mac-server set allowed-interface-list=LAN")
    (out "/tool mac-server mac-winbox set allowed-interface-list=LAN")
    (out)

    (out "# --- CA certificates (required before DoH) ---")
    (out "# Ensure wifi1 is associated with the upstream AP before running these.")
    (out "# /tool fetch url=https://curl.se/ca/cacert.pem")
    (out "# /certificate import file-name=cacert.pem")
    (out)

    (out "# --- DNS ---")
    (out "/ip dns set allow-remote-requests=yes "
         "servers=1.1.1.3,1.0.0.3 "
         "use-doh-server=\"https://dns.nextdns.io/" nextdns-id "/" nextdns-name "\" "
         "verify-doh-cert=yes")
    (out "/ip dns static add name=router.lan address=192.168.88.1 type=A comment=defconf")
    (out "/ip dns static add name=dns.nextdns.io address=45.90.28.0  type=A")
    (out "/ip dns static add name=dns.nextdns.io address=45.90.30.0  type=A")
    (out "/ip dns static add name=dns.nextdns.io address=2a07:a8c0:: type=AAAA")
    (out "/ip dns static add name=dns.nextdns.io address=2a07:a8c1:: type=AAAA")
    (out)

    (out "# --- NAT ---")
    (out "/ip firewall nat add action=masquerade chain=srcnat "
         "comment=\"defconf: masquerade\" ipsec-policy=out,none out-interface-list=WAN")
    (out)

    (out "# --- WireGuard (AirVPN IPv6 tunnel) ---")
    (out "/interface wireguard add name=airvpn "
         "private-key=\"" private-key "\" "
         "listen-port=" wg-port " "
         "mtu=" mtu)
    (out "/interface wireguard peers add interface=airvpn "
         "public-key=\"" server-pubkey "\" "
         "preshared-key=\"" preshared-key "\" "
         "endpoint-address=" endpoint-ip " "
         "endpoint-port=" endpoint-port " "
         "allowed-address=::/0 "
         "persistent-keepalive=" keepalive "s")
    (out)

    (out "# --- IPv6 ---")
    (out "/ipv6 address add address=" tunnel-ipv6 " interface=airvpn advertise=no")
    (out "/ipv6 route add dst-address=::/0 gateway=airvpn")
    (out "/ipv6 address add address=" lan-ula " interface=bridge advertise=yes")
    (out "/ipv6 firewall nat add action=masquerade chain=srcnat "
         "out-interface=airvpn comment=\"airvpn ipv6 masquerade\"")
    (out "/ipv6 nd add interface=bridge ra-lifetime=1800 advertise-dns=yes other-configuration=no")
    (out)

    (out "# --- Allow WireGuard UDP through IPv4 input firewall ---")
    (out "/ip firewall filter add action=accept chain=input "
         "comment=\"allow AirVPN WireGuard UDP\" "
         "protocol=udp dst-port=" wg-port " "
         "in-interface-list=WAN "
         "place-before=[find comment=\"defconf: drop all not coming from LAN\"]")))

(define (main)
  (let ((args (cdr (command-line))))
    (when (null? args)
      (die "Usage: guile generate-rsc.scm <env-file>"))
    (generate (read-env (car args)))))

(main)
