#!/usr/bin/env bash
# generate-rsc.sh — Read an env file and emit a RouterOS setup script to stdout.
#
# Usage: bash generate-rsc.sh <env-file> > setup.rsc
set -euo pipefail

die() { printf 'error: %s\n' "$*" >&2; exit 1; }

[[ $# -eq 1 ]] || die "Usage: $0 <env-file>"
env_file="$1"

[[ -f "$env_file" ]] || die "Missing $env_file — copy .env.example and fill in values"

env_get() {
    local key="$1"
    local val
    val=$(grep -m1 "^${key}=" "$env_file" | cut -d= -f2-) || true
    printf '%s' "$val"
}

required() {
    local key="$1"
    local val
    val=$(env_get "$key")
    [[ -n "$val" ]] || die "Required variable not set in $env_file: $key"
    printf '%s' "$val"
}

optional() {
    local key="$1"
    local default="$2"
    local val
    val=$(env_get "$key")
    printf '%s' "${val:-$default}"
}

upstream_ssid=$(required UPSTREAM_SSID)
upstream_pass=$(required UPSTREAM_WIFI_PASSWORD)
travel_ssid=$(required TRAVEL_SSID)
travel_pass=$(required TRAVEL_WIFI_PASSWORD)
nextdns_id=$(required NEXTDNS_PROFILE_ID)
device_name=$(required DEVICE_NAME)
nextdns_name=$(optional NEXTDNS_DEVICE_NAME "$device_name")
wg_port=$(optional WG_LISTEN_PORT 13231)
lan_ula=$(optional LAN_ULA_PREFIX fd88:1::1/64)
private_key=$(required EXIT_PRIVATE_KEY)
mtu=$(optional EXIT_MTU 1320)
server_pubkey=$(required EXIT_SERVER_PUBKEY)
preshared_key=$(required EXIT_PRESHARED_KEY)
endpoint_ip=$(required EXIT_ENDPOINT_IP)
endpoint_port=$(required EXIT_ENDPOINT_PORT)
keepalive=$(optional EXIT_KEEPALIVE 15)
tunnel_ipv6=$(required EXIT_TUNNEL_IPV6)

cat <<EOF
# Generated by generate-rsc.sh
# Model: hAP ax2 (C52iG-5HaxD2HaxD)

# --- Identity ---
/system identity set name=${device_name}
/system note set show-at-login=no
/system ntp client set enabled=yes
/system ntp client servers add address=pool.ntp.org

# --- Users ---
/user add name=root group=full
# From your local machine, push your SSH public key:
# ssh -4 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@192.168.88.1 \\
#   "/file print file=mykey.txt; file set mykey.txt contents=\"\$(cat ~/.ssh/id_ed25519.pub)\"; /user ssh-keys import public-key-file=mykey.txt"

# --- Bridge ---
/interface bridge add name=bridge comment=defconf

# --- WiFi security profiles ---
/interface wifi security
add name=Upstream passphrase="${upstream_pass}" ft=no
add name=Travel   passphrase="${travel_pass}"

# --- WiFi interfaces ---
/interface wifi
set [find default-name=wifi1] channel.band=5ghz-ax channel.skip-dfs-channels=all configuration.mode=station-bridge configuration.ssid="${upstream_ssid}" security=Upstream security.ft=no security.ft-over-ds=no disabled=no
set [find default-name=wifi2] disabled=yes
add name=wifiTravel master-interface=wifi1 configuration.mode=ap configuration.ssid="${travel_ssid}" security=Travel disabled=no

# --- Bridge ports ---
/interface bridge port
remove [find interface=wifi1]
add bridge=bridge interface=wifiTravel

# --- Interface lists ---
/interface list member
add interface=wifi1  list=WAN
add interface=exit list=WAN

# --- WAN DHCP client ---
/ip dhcp-client add interface=wifi1 default-route-tables=main name=wan-dhcp comment=defconf

# --- Management restrictions ---
/ip neighbor discovery-settings set discover-interface-list=LAN
/tool mac-server set allowed-interface-list=LAN
/tool mac-server mac-winbox set allowed-interface-list=LAN

# --- CA certificates (required before DoH) ---
# Ensure wifi1 is associated with the upstream AP before running these.
# /tool fetch url=https://curl.se/ca/cacert.pem
# /certificate import file-name=cacert.pem

# --- DNS ---
/ip dns set allow-remote-requests=yes servers=1.1.1.3,1.0.0.3 use-doh-server="https://dns.nextdns.io/${nextdns_id}/${nextdns_name}" verify-doh-cert=yes
/ip dns static add name=router.lan address=192.168.88.1 type=A comment=defconf
/ip dns static add name=dns.nextdns.io address=45.90.28.0  type=A
/ip dns static add name=dns.nextdns.io address=45.90.30.0  type=A
/ip dns static add name=dns.nextdns.io address=2a07:a8c0:: type=AAAA
/ip dns static add name=dns.nextdns.io address=2a07:a8c1:: type=AAAA

# --- NAT ---
/ip firewall nat add action=masquerade chain=srcnat comment="defconf: masquerade" ipsec-policy=out,none out-interface-list=WAN

# --- WireGuard (IPv6 exit tunnel) ---
/interface wireguard add name=exit private-key="${private_key}" listen-port=${wg_port} mtu=${mtu}
/interface wireguard peers add interface=exit public-key="${server_pubkey}" preshared-key="${preshared_key}" endpoint-address=${endpoint_ip} endpoint-port=${endpoint_port} allowed-address=::/0 persistent-keepalive=${keepalive}s

# --- IPv6 ---
/ipv6 address add address=${tunnel_ipv6} interface=exit advertise=no
/ipv6 route add dst-address=::/0 gateway=exit
/ipv6 address add address=${lan_ula} interface=bridge advertise=yes
/ipv6 firewall nat add action=masquerade chain=srcnat out-interface=exit comment="exit ipv6 masquerade"
/ipv6 nd add interface=bridge ra-lifetime=1800 advertise-dns=yes other-configuration=no

# --- Allow WireGuard UDP through IPv4 input firewall ---
/ip firewall filter add action=accept chain=input comment="allow WireGuard exit UDP" protocol=udp dst-port=${wg_port} in-interface-list=WAN place-before=[find comment="defconf: drop all not coming from LAN"]
EOF
